### ISSUE TITLE
文档输出路径写错了，还有是否能提供选项，下载后不重命名

### ISSUE THREAD

**Issue by lx8s8** [xiazunyang/reinforcer#1]
outputDirection -> outputDirectory

**Comment by xiazunyang** [comment]
感谢提醒。
下载重命名的功能其实是有的，但是适用性并不强。先说一下我们的项目中的用法：
通过在app模块下的build.gradle中添加以下代码来设置打包后的apk的名称，让打包后的名称为渠道名.apk
```
applicationVariants.all { variant ->
        variant.outputs.all { output ->
            String variantName = variant.baseName
            outputFileName = variantName.substring(0, variantName.indexOf('-')) + ".apk"
        }
    }
```
然后360加固助手加固后的文件名一般是原文件名_xxx_jiagu_sign.apk，插件会直接截取第一个_字符之前的内容作为文件名。
综上所述，也就是outputFileName是什么，加固后的文件名就是什么，前提是outputFileName里面不包含_字符。
最后reinforcer的配置还有个rename的map，如果该map中有key与该文件名相同，则将该文件重命名为对应的value值。
这个重命名的功能目前是能满足我这边的需求，你可以详细讲下你那边具体的需求。

**Comment by lx8s8** [comment]
嗯我看了代码，我是输出的自定义名字，但是因为我们命名规则里面带有-_等符号，被rename直接截取了，这个rename的map，我在build.gradle里面配置后一直没编译过，现在换了命名方式后正常了

**Comment by xiazunyang** [comment]
直接添加map到remane上就行：
```
reinforcer {
    ...
    rename += ["key1": "value1", "key2": "value2"]
}
```

**Comment by lx8s8** [comment]
3Q,已经解决了，但是rename这个函数我还是调用不了

**Comment by xiazunyang** [comment]
非常抱歉，上述的rename的使用方法是错误的。
其实一共是有3种使用方法：
```
//直接操作renameMap
renameMap.putAll(
            ["key1": "value1", "key2": "value2" ]
    )

//kotlin添加方式，需要创建Pair，非kts不推荐使用
rename(new kotlin.Pair("key1", "value1"), new kotlin.Pair("key2", "value2"))

//另一种rename，奇数下标的是key，偶数下标的是value
rename("key1", "value1", "key2", "value2")
```
