### ISSUE TITLE
Gradle执行命令失败,还望大佬解答一下

### ISSUE THREAD

**Issue by lydlovezjr** [xiazunyang/reinforcer#7]
<img width="914" alt="微信截图_20220629150325" src="https://user-images.githubusercontent.com/19246347/176373035-362eddd6-26b8-4113-a58a-530cd3def95f.png">
<img width="581" alt="微信截图_20220629150221" src="https://user-images.githubusercontent.com/19246347/176373044-8f963c43-d38b-4c7f-b6ee-801eb720f091.png">

**Comment by xiazunyang** [comment]
instanllationPath应该是以`//jiagu.jar`结尾，它指向该jar包，而不是安装目录。

**Comment by lydlovezjr** [comment]
免费的不能用了吗,大佬
<img width="863" alt="微信截图_20220629155605" src="https://user-images.githubusercontent.com/19246347/176383279-2eac8283-a1c0-4257-9b32-3cefddc32dc3.png">

**Comment by lydlovezjr** [comment]
果然,免费用不成了
https://jiagu.360.cn/#/global/announcement/114
<img width="914" alt="微信截图_20220629161424" src="https://user-images.githubusercontent.com/19246347/176386974-66e999be-ebf3-4ec5-8bd3-c94902451052.png">
